pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                echo 'Cloning repository...'
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling Java program...'
                sh 'javac CalculatorMain.java'
            }
        }

        stage('Run') {
            steps {
                echo 'Running Java program...'
                sh 'java CalculatorMain'
            }
        }
    }
}