pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('calculator') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Run') {
            steps {
                dir('calculator') {
                    bat 'mvn exec:java -Dexec.mainClass=calculator.CalculatorMain'
                }
            }
        }
    }
}